name: 'setup python dependencies'
description: 'sets up python with uv and installs dependencies with caching'

inputs:
  python-version:
    description: 'python version to use'
    required: true
  install-dev:
    description: 'whether to install dev dependencies'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          requirements.txt
          requirements-dev.txt
    
    - name: cache uv packages
      uses: actions/cache@v4
      id: uv-cache
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-uv-
    
    - name: install uv
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install uv
    
    - name: install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.install-dev }}" = "true" ]; then
          uv pip install --system -r requirements-dev.txt
        else
          uv pip install --system -r requirements.txt
        fi
