# flare+ configuration

data_ingestion:
  cache_hours: 48
  update_interval_minutes: 60
  backfill_start_date: "2023-01-01"
  
  # noaa/swpc public endpoints
  endpoints:
    goes_xrs_7day: "https://services.swpc.noaa.gov/json/goes/primary/xrays-7-day.json"
    goes_xrs_6hour: "https://services.swpc.noaa.gov/json/goes/primary/xrays-6-hour.json"
    solar_regions: "https://services.swpc.noaa.gov/json/solar_regions.json"
    # historical data from noaa archives
    goes_archive: "https://www.ncei.noaa.gov/data/goes-space-environment-monitor/access/avg/"
    # magnetogram data sources
    # note: noaa swpc doesn't provide direct magnetogram json endpoints
    # solar regions endpoint includes magnetic_type field
    # for full magnetogram data, use nasa sdo/hmi (jsoc) api
    sdo_hmi_info: "https://jsoc.stanford.edu/ajax/lookdata.html"

database:
  table_prefix: "flare_"
  schema_version: "1.0"

feature_engineering:
  rolling_windows: [6, 12, 24]  # hours
  flux_bands: ["short", "long"]  # xrs channels
  flare_classes: ["B", "C", "M", "X"]

model:
  target_windows: [24, 48]  # hours ahead
  classes: ["None", "C", "M", "X"]
  test_size: 0.2
  cv_folds: 5
  random_state: 42

